[package]
name = "resonate-vault"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flacenc.workspace = true
image.workspace = true
jxl-oxide.workspace = true
parking_lot.workspace = true
resonate-codec.workspace = true
resonate-core.workspace = true
symphonia.workspace = true
thiserror.workspace = true
tracing.workspace = true
zstd.workspace = true
zune-core.workspace = true
zune-jpegxl.workspace = true

[lints]
workspace = true
