[package]
name = "resonate-mpris"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
resonate-core.workspace = true
resonate-engine.workspace = true
thiserror.workspace = true
tracing.workspace = true
zbus.workspace = true

[dev-dependencies]
resonate-codec.workspace = true

[lints]
workspace = true
