[package]
name = "resonate-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
chardetng.workspace = true
encoding_rs.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
