[package]
name = "resonate-codec"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ape-decoder.workspace = true
image.workspace = true
lofty.workspace = true
opus-rs.workspace = true
parking_lot.workspace = true
resonate-core.workspace = true
rustix.workspace = true
symphonia.workspace = true
symphonia-codec-wavpack.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
