[package]
name = "resonate-pipewire"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossbeam-channel.workspace = true
libspa.workspace = true
parking_lot.workspace = true
pipewire.workspace = true
resonate-core.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
