mod analysis;
mod browser;
mod chrome;
pub(crate) mod dropping;
mod favourites;
pub(crate) mod field;
mod focus;
mod gives_way;
mod hint;
mod inspector;
pub(crate) mod kit;
mod listen;
mod listing;
mod lyrics;
pub(crate) mod menu;
mod missing;
mod mosaic;
mod part;
mod playlists;
pub(crate) mod plot;
mod pointed;
mod queue;
mod reorder;
mod root;
mod scrollbar;
mod search;
pub(crate) mod settings;
mod slider;
pub(crate) mod sorting;
pub(crate) mod statistics;
mod suggestions;
pub(crate) mod transport;
mod typing;
pub(crate) mod visualiser;

pub use crate::views::root::{Pane, RootView};
