mod analysis;
mod browser;
mod chrome;
mod favourites;
pub(crate) mod field;
mod focus;
mod hint;
mod inspector;
pub(crate) mod kit;
mod listen;
mod listing;
mod lyrics;
pub(crate) mod menu;
mod missing;
mod playlists;
mod pointed;
mod queue;
mod reorder;
mod root;
mod settings;
mod slider;
pub(crate) mod sorting;
pub(crate) mod statistics;
mod suggestions;
pub(crate) mod transport;
mod typing;
mod visualiser;

pub use crate::views::root::{Pane, RootView};
