use std::{fmt, time::Duration};

use ahash::AHashSet;
use resonate_core::{AlbumId, ArtistId, Isrc, Mbid, Service, TrackId};
use rusqlite::{Connection, OptionalExtension as _, params};

use crate::{
    ArtistFound, BarcodeMatch, Credit, Error, Found, Recording, RecordingAsked, RecordingMatch,
    Reference, Result, StoreOp, Wording,
    enrich::{self, NamedAs},
    enriched::folded_title,
    reference::credited_as,
    share, store,
};

const SECURE: &str = "https://";
const PLAIN: &str = "http://";
const SPOTIFY_TRACK: &str = "spotify:track:";
const SPOTIFY_TRACK_PAGE: &str = "https://open.spotify.com/track/";
const SPOTIFY_ALBUM: &str = "spotify:album:";
const SPOTIFY_ALBUM_PAGE: &str = "https://open.spotify.com/album/";
const SPOTIFY_ARTIST: &str = "spotify:artist:";
const SPOTIFY_PLAYLIST: &str = "spotify:playlist:";
const APPLE_MUSIC_PLAYLIST: &str = "pl.";
const SPOTIFY_ID_LENGTH: usize = 22;
const DEEZER_ARTIST_PAGE: &str = "https://www.deezer.com/artist/";
const APPLE_MUSIC_IN_EVERY_STOREFRONT: &str = "us";
const SONG_LINK_PAGES: &str = "https://song.link/";
const ALBUM_LINK_PAGES: &str = "https://album.link/";
const YOUTUBE_MUSIC_ALBUMS: &str = "OLAK5uy_";
const HELD_BY_RECORDING: &str =
    "SELECT title, artist, id FROM tracks WHERE mbid = ?1 ORDER BY id LIMIT 1";
const HELD_BY_ISRC: &str =
    "SELECT title, artist, id FROM tracks WHERE isrc = ?1 ORDER BY id LIMIT 1";
const HELD_ALBUM: &str = "SELECT a.id, coalesce(a.release_title, a.title),
        (SELECT r.name FROM artists r WHERE r.id = a.artist_id),
        (SELECT count(*) FROM release_tracks m WHERE m.album_id = a.id AND m.track_id IS NULL)
   FROM albums a
  WHERE (a.release_group = ?1 OR a.mbid = ?2)
    AND EXISTS (SELECT 1 FROM tracks t WHERE t.album_id = a.id)
  ORDER BY coalesce(a.mbid = ?2, 0) DESC, a.id
  LIMIT 1";
pub(crate) const LENGTHS_AGREE_WITHIN: Duration = Duration::from_secs(5);
const SOUNDCLOUD_PAGES_NAMING_NO_ARTIST: [&str; 14] = [
    "discover",
    "search",
    "stream",
    "you",
    "upload",
    "charts",
    "pages",
    "settings",
    "messages",
    "notifications",
    "people",
    "tags",
    "stations",
    "feed",
];
const SOUNDCLOUD_PAGES_NAMING_NO_SONG: [&str; 9] = [
    "sets",
    "likes",
    "tracks",
    "albums",
    "reposts",
    "followers",
    "following",
    "popular-tracks",
    "comments",
];
const BETWEEN_ARTIST_AND_TITLE: &str = " - ";
const AN_AUTOGENERATED_CHANNEL: &str = " - Topic";
const VIDEO_QUALIFIERS: [&str; 26] = [
    "official",
    "officialvideo",
    "officialmusicvideo",
    "musicvideo",
    "video",
    "videoclip",
    "officialvideoclip",
    "clipofficiel",
    "officialaudio",
    "audio",
    "officiallyricvideo",
    "lyricvideo",
    "officiallyrics",
    "lyrics",
    "lyric",
    "officialvisualizer",
    "officialvisualiser",
    "visualizer",
    "visualiser",
    "officialhdvideo",
    "hdvideo",
    "hd",
    "hq",
    "4k",
    "officialmv",
    "mv",
];
const BARCODE_DIGITS_AT_LEAST: usize = 8;
const BARCODE_DIGITS_AT_MOST: usize = 14;
const UPC_DIGITS: usize = 12;
const EAN_DIGITS: usize = 13;
const PADDING: char = '0';

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SongLink {
    MusicBrainz(Mbid),
    Deezer(u64),
    Elsewhere(String),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AlbumLink {
    Release(Mbid),
    Group(Mbid),
    Deezer(u64),
    Elsewhere(String),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ArtistLink {
    MusicBrainz(Mbid),
    Deezer(u64),
    Elsewhere(String),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PlaylistLink {
    Deezer(u64),
    ListenBrainz(Mbid),
    Spotify(String),
    AppleMusic { storefront: String, id: String },
    Youtube(String),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FollowedLink {
    Song(SongLink),
    Album(AlbumLink),
    Artist(ArtistLink),
    Playlist(PlaylistLink),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ListedSong {
    Recording(Mbid),
    Named(LinkNames),
    Uploaded(LinkNames),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LinkedPlaylist {
    pub name: String,
    pub songs: Vec<ListedSong>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FollowedPlaylist {
    pub name: String,
    pub held: Vec<TrackId>,
    pub found: Vec<Found>,
    pub unnamed: usize,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Barcode(String);

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LinkNames {
    pub isrcs: Vec<Isrc>,
    pub length: Option<Duration>,
    pub title: Option<String>,
    pub artist: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AlbumNames {
    pub barcodes: Vec<Barcode>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Linked {
    Held {
        track: TrackId,
        title: String,
        artist: Option<String>,
    },
    Found(Box<Found>),
    HeldAlbum {
        album: AlbumId,
        title: String,
        artist: Option<String>,
        missing: u32,
    },
    Album {
        group: Mbid,
        release: Option<Mbid>,
        title: String,
        artist: Option<String>,
    },
    HeldArtist {
        artist: ArtistId,
        name: String,
    },
    Artist(ArtistFound),
    Unnamed,
}

struct Address<'a> {
    rest: &'a str,
    host: String,
    segments: Vec<&'a str>,
    query: &'a str,
}

impl<'a> Address<'a> {
    fn read(text: &'a str) -> Option<Self> {
        let rest = text
            .strip_prefix(SECURE)
            .or_else(|| text.strip_prefix(PLAIN))?;
        let rest = rest.split('#').next().unwrap_or(rest);
        let (address, query) = rest.split_once('?').unwrap_or((rest, ""));
        let (host, path) = address.split_once('/').unwrap_or((address, ""));
        let host = host.to_ascii_lowercase();
        let host = host.strip_prefix("www.").unwrap_or(&host).to_owned();
        let segments = path
            .split('/')
            .filter(|segment| !segment.is_empty())
            .collect();

        Some(Self {
            rest,
            host,
            segments,
            query,
        })
    }

    fn is_on_musicbrainz(&self) -> bool {
        self.host == "musicbrainz.org" || self.host.ends_with(".musicbrainz.org")
    }

    fn after(&self, page: &str) -> Option<&'a str> {
        self.segments
            .windows(2)
            .find(|pair| pair[0] == page)
            .map(|pair| pair[1])
    }

    fn names_an_id_after(&self, page: &str) -> bool {
        self.segments
            .windows(2)
            .any(|pair| pair[0] == page && names_an_id(pair[1]))
    }

    fn first(&self) -> Option<&'a str> {
        self.segments.first().copied()
    }

    fn elsewhere(&self) -> String {
        format!("{SECURE}{}", self.rest)
    }
}

fn one_token(text: &str) -> Option<&str> {
    let text = text.trim();
    (!text.is_empty() && !text.contains(char::is_whitespace)).then_some(text)
}

impl SongLink {
    pub fn read(text: &str) -> Option<Self> {
        let text = one_token(text)?;
        if let Some(id) = text.strip_prefix(SPOTIFY_TRACK) {
            return names_an_id(id).then(|| Self::Elsewhere(format!("{SPOTIFY_TRACK_PAGE}{id}")));
        }
        let address = Address::read(text)?;

        if address.is_on_musicbrainz() {
            return match address.segments.as_slice() {
                ["recording", id, ..] => Mbid::new(id).ok().map(Self::MusicBrainz),
                _ => None,
            };
        }
        if address.host == "deezer.com" {
            return address.after("track")?.parse().ok().map(Self::Deezer);
        }

        names_a_song(&address).then(|| Self::Elsewhere(address.elsewhere()))
    }

    pub fn page(&self) -> Option<String> {
        match self {
            Self::Elsewhere(url) if url.starts_with(SONG_LINK_PAGES) => Some(url.clone()),
            Self::Elsewhere(url) => Some(format!(
                "{SONG_LINK_PAGES}{}",
                share::escaped_for_a_path(url)
            )),
            Self::MusicBrainz(_) | Self::Deezer(_) => None,
        }
    }
}

impl AlbumLink {
    pub fn read(text: &str) -> Option<Self> {
        let text = one_token(text)?;
        if let Some(id) = text.strip_prefix(SPOTIFY_ALBUM) {
            return names_an_id(id).then(|| Self::Elsewhere(format!("{SPOTIFY_ALBUM_PAGE}{id}")));
        }
        let address = Address::read(text)?;

        if address.is_on_musicbrainz() {
            return match address.segments.as_slice() {
                ["release", id, ..] => Mbid::new(id).ok().map(Self::Release),
                ["release-group", id, ..] => Mbid::new(id).ok().map(Self::Group),
                _ => None,
            };
        }
        if address.host == "deezer.com" {
            return address.after("album")?.parse().ok().map(Self::Deezer);
        }

        names_an_album(&address).then(|| Self::Elsewhere(address.elsewhere()))
    }

    pub fn page(&self) -> Option<String> {
        match self {
            Self::Elsewhere(url) if url.starts_with(ALBUM_LINK_PAGES) => Some(url.clone()),
            Self::Elsewhere(url) => Some(format!(
                "{ALBUM_LINK_PAGES}{}",
                share::escaped_for_a_path(url)
            )),
            Self::Release(_) | Self::Group(_) | Self::Deezer(_) => None,
        }
    }
}

impl ArtistLink {
    pub fn read(text: &str) -> Option<Self> {
        let text = one_token(text)?;
        if let Some(id) = text.strip_prefix(SPOTIFY_ARTIST) {
            return names_an_id(id)
                .then(|| Self::Elsewhere(format!("https://open.spotify.com/artist/{id}")));
        }
        let address = Address::read(text)?;

        if address.is_on_musicbrainz() {
            return match address.segments.as_slice() {
                ["artist", id, ..] => Mbid::new(id).ok().map(Self::MusicBrainz),
                _ => None,
            };
        }
        if address.host == "deezer.com" {
            return address.after("artist")?.parse().ok().map(Self::Deezer);
        }
        artist_page(&address).map(Self::Elsewhere)
    }

    pub fn pages(&self) -> Vec<String> {
        match self {
            Self::MusicBrainz(_) => Vec::new(),
            Self::Deezer(artist) => vec![format!("{DEEZER_ARTIST_PAGE}{artist}")],
            Self::Elsewhere(page) => {
                let in_every_storefront = apple_music_storefront(page)
                    .filter(|storefront| *storefront != APPLE_MUSIC_IN_EVERY_STOREFRONT)
                    .map(|storefront| {
                        page.replacen(
                            &format!("/{storefront}/"),
                            &format!("/{APPLE_MUSIC_IN_EVERY_STOREFRONT}/"),
                            1,
                        )
                    });
                std::iter::once(page.clone())
                    .chain(in_every_storefront)
                    .collect()
            }
        }
    }
}

fn apple_music_storefront(page: &str) -> Option<&str> {
    page.strip_prefix("https://music.apple.com/")?
        .split('/')
        .next()
}

fn artist_page(address: &Address<'_>) -> Option<String> {
    let segments = address.segments.as_slice();
    let id_after = |page: &str| address.after(page).filter(|id| names_an_id(id));

    match address.host.as_str() {
        "open.spotify.com" | "play.spotify.com" => {
            id_after("artist").map(|id| format!("https://open.spotify.com/artist/{id}"))
        }
        "tidal.com" | "listen.tidal.com" => {
            id_after("artist").map(|id| format!("https://tidal.com/artist/{id}"))
        }
        "music.apple.com" | "itunes.apple.com" => {
            let storefront = segments
                .first()
                .filter(|storefront| storefront.len() == 2)
                .unwrap_or(&APPLE_MUSIC_IN_EVERY_STOREFRONT);
            segments
                .iter()
                .position(|segment| *segment == "artist")
                .and_then(|at| segments[at + 1..].last())
                .map(|id| id.trim_start_matches("id"))
                .filter(|id| !id.is_empty() && id.bytes().all(|byte| byte.is_ascii_digit()))
                .map(|id| format!("https://music.apple.com/{storefront}/artist/{id}"))
        }
        "music.youtube.com" => {
            id_after("channel").map(|id| format!("https://music.youtube.com/channel/{id}"))
        }
        "youtube.com" | "m.youtube.com" => {
            id_after("channel").map(|id| format!("https://www.youtube.com/channel/{id}"))
        }
        "soundcloud.com" | "m.soundcloud.com" => match segments {
            [account]
                if !SOUNDCLOUD_PAGES_NAMING_NO_ARTIST.contains(account) && names_an_id(account) =>
            {
                Some(format!(
                    "https://soundcloud.com/{}",
                    account.to_ascii_lowercase()
                ))
            }
            _ => None,
        },
        host if host.ends_with(".bandcamp.com") && segments.is_empty() => {
            Some(format!("https://{host}/"))
        }
        host if host.starts_with("music.amazon.") => {
            id_after("artists").map(|id| format!("https://music.amazon.com/artists/{id}"))
        }
        _ => None,
    }
}

impl FollowedLink {
    pub fn read(text: &str) -> Option<Self> {
        SongLink::read(text)
            .map(Self::Song)
            .or_else(|| AlbumLink::read(text).map(Self::Album))
            .or_else(|| ArtistLink::read(text).map(Self::Artist))
            .or_else(|| PlaylistLink::read(text).map(Self::Playlist))
    }
}

impl PlaylistLink {
    pub fn read(text: &str) -> Option<Self> {
        let text = one_token(text)?;
        if let Some(id) = text.strip_prefix(SPOTIFY_PLAYLIST) {
            return names_a_spotify_id(id).then(|| Self::Spotify(id.to_owned()));
        }
        let address = Address::read(text)?;

        match address.host.as_str() {
            "open.spotify.com" => address
                .after("playlist")
                .filter(|id| names_a_spotify_id(id))
                .map(|id| Self::Spotify(id.to_owned())),
            "deezer.com" => address.after("playlist")?.parse().ok().map(Self::Deezer),
            "listenbrainz.org" => match address.segments.as_slice() {
                ["playlist", id, ..] => Mbid::new(id).ok().map(Self::ListenBrainz),
                _ => None,
            },
            "youtube.com" | "m.youtube.com" | "music.youtube.com" => (address.first()
                == Some("playlist"))
            .then(|| asked_for(address.query, "list"))
            .flatten()
            .filter(|list| names_an_id(list) && !list.starts_with(YOUTUBE_MUSIC_ALBUMS))
            .map(|list| Self::Youtube(list.to_owned())),
            "music.apple.com" => match address.segments.as_slice() {
                [storefront, "playlist", .., id] if names_a_storefront(storefront) => {
                    names_an_apple_music_playlist(id).then(|| Self::AppleMusic {
                        storefront: (*storefront).to_owned(),
                        id: (*id).to_owned(),
                    })
                }
                _ => None,
            },
            _ => None,
        }
    }
}

fn names_a_storefront(storefront: &str) -> bool {
    storefront.len() == 2 && storefront.chars().all(|letter| letter.is_ascii_lowercase())
}

fn names_an_apple_music_playlist(id: &str) -> bool {
    id.strip_prefix(APPLE_MUSIC_PLAYLIST).is_some_and(|rest| {
        !rest.is_empty()
            && rest
                .chars()
                .all(|glyph| glyph.is_ascii_alphanumeric() || glyph == '-')
    })
}

const HELD_UNDER_THE_ID: &str = "SELECT id, name FROM artists WHERE mbid = ?1 ORDER BY id LIMIT 1";

const HELD_UNDER_THE_NAME: &str = "SELECT id, name FROM artists WHERE key = ?1";

pub(crate) enum ArtistHeldBy<'a> {
    Id(&'a Mbid),
    Name(&'a str),
}

pub(crate) fn artist_held(connection: &Connection, by: ArtistHeldBy<'_>) -> Result<Option<Linked>> {
    let (sql, asked) = match by {
        ArtistHeldBy::Id(mbid) => (HELD_UNDER_THE_ID, mbid.as_str().to_owned()),
        ArtistHeldBy::Name(name) => (HELD_UNDER_THE_NAME, store::folded_letters(name)),
    };
    connection
        .query_row(sql, params![asked], |row| {
            Ok((row.get::<_, i64>(0)?, row.get::<_, String>(1)?))
        })
        .optional()
        .map_err(|source| Error::store(StoreOp::Query, source))?
        .map(|(id, name)| {
            Ok(Linked::HeldArtist {
                artist: ArtistId::new(id as u64)?,
                name,
            })
        })
        .transpose()
}

pub fn is_a_followed_link(text: &str) -> bool {
    FollowedLink::read(text).is_some()
}

impl Barcode {
    pub fn new(text: &str) -> Option<Self> {
        let digits = text.trim();
        let counted = BARCODE_DIGITS_AT_LEAST..=BARCODE_DIGITS_AT_MOST;

        (counted.contains(&digits.len()) && digits.bytes().all(|byte| byte.is_ascii_digit()))
            .then(|| Self(digits.to_owned()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    pub fn names(&self, stated: &str) -> bool {
        let stated = stated.trim();
        stated.bytes().all(|byte| byte.is_ascii_digit())
            && stated.trim_start_matches(PADDING) == self.0.trim_start_matches(PADDING)
    }

    pub fn spellings(&self) -> Vec<String> {
        let significant = self.0.trim_start_matches(PADDING);
        let mut spellings = vec![self.0.clone()];
        for width in [UPC_DIGITS, EAN_DIGITS] {
            let spelt = format!("{significant:0>width$}");
            if !spellings.contains(&spelt) {
                spellings.push(spelt);
            }
        }
        spellings
    }
}

impl fmt::Display for Barcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

fn names_a_song(address: &Address<'_>) -> bool {
    let first = address.first();
    let segments = address.segments.as_slice();

    match address.host.as_str() {
        "open.spotify.com" | "play.spotify.com" | "tidal.com" | "listen.tidal.com" => {
            address.names_an_id_after("track")
        }
        "music.apple.com" | "itunes.apple.com" => {
            asked_for(address.query, "i").is_some_and(names_an_id) || segments.contains(&"song")
        }
        "youtube.com" | "m.youtube.com" | "music.youtube.com" => {
            first == Some("watch") && asked_for(address.query, "v").is_some_and(names_an_id)
        }
        "youtu.be" => segments.len() == 1 && names_an_id(segments[0]),
        "soundcloud.com" | "m.soundcloud.com" => match segments {
            [_, track] => !SOUNDCLOUD_PAGES_NAMING_NO_SONG.contains(track),
            _ => false,
        },
        "song.link" => !segments.is_empty(),
        "play.anghami.com" => address.names_an_id_after("song"),
        "boomplay.com" => address.names_an_id_after("songs"),
        "audiomack.com" => segments.get(1) == Some(&"song"),
        host if host.starts_with("music.amazon.") => {
            first == Some("tracks") || asked_for(address.query, "trackAsin").is_some()
        }
        host if host.starts_with("music.yandex.") => address.names_an_id_after("track"),
        _ => false,
    }
}

fn names_an_album(address: &Address<'_>) -> bool {
    match address.host.as_str() {
        "open.spotify.com" | "play.spotify.com" | "tidal.com" | "listen.tidal.com" => {
            address.names_an_id_after("album")
        }
        "music.apple.com" | "itunes.apple.com" => {
            address.names_an_id_after("album") && asked_for(address.query, "i").is_none()
        }
        "music.youtube.com" => {
            address.first() == Some("playlist")
                && asked_for(address.query, "list")
                    .is_some_and(|list| list.starts_with(YOUTUBE_MUSIC_ALBUMS) && names_an_id(list))
        }
        "album.link" => !address.segments.is_empty(),
        host if host.starts_with("music.amazon.") => {
            address.names_an_id_after("albums") && asked_for(address.query, "trackAsin").is_none()
        }
        _ => false,
    }
}

fn names_a_spotify_id(id: &str) -> bool {
    id.len() == SPOTIFY_ID_LENGTH && id.bytes().all(|byte| byte.is_ascii_alphanumeric())
}

fn names_an_id(id: &str) -> bool {
    !id.is_empty()
        && id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
}

fn asked_for<'a>(query: &'a str, name: &str) -> Option<&'a str> {
    query
        .split('&')
        .find_map(|pair| pair.strip_prefix(name)?.strip_prefix('='))
}

pub(crate) enum HeldBy<'a> {
    Recording(&'a Mbid),
    Isrc(&'a Isrc),
}

pub(crate) fn held_as(connection: &Connection, held_by: HeldBy<'_>) -> Result<Option<Linked>> {
    let (sql, key) = match held_by {
        HeldBy::Recording(recording) => (HELD_BY_RECORDING, recording.as_str()),
        HeldBy::Isrc(isrc) => (HELD_BY_ISRC, isrc.as_str()),
    };

    connection
        .query_row(sql, params![key], |row| {
            Ok((row.get(0)?, row.get(1)?, row.get::<_, i64>(2)?))
        })
        .optional()
        .map_err(|source| Error::store(StoreOp::Query, source))?
        .map(|(title, artist, id)| {
            Ok(Linked::Held {
                track: TrackId::new(id as u64)?,
                title,
                artist,
            })
        })
        .transpose()
}

pub(crate) fn the_take_linked(
    takes: Vec<Recording>,
    length: Option<Duration>,
) -> Option<Recording> {
    let Some(length) = length else {
        return takes.into_iter().next();
    };
    let apart = |take: &Recording| take.length.map(|held| held.abs_diff(length));

    takes
        .into_iter()
        .filter(|take| apart(take).is_none_or(|apart| apart <= LENGTHS_AGREE_WITHIN))
        .min_by_key(|take| apart(take).unwrap_or(LENGTHS_AGREE_WITHIN))
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct Reading {
    title: String,
    artist: String,
}

impl Reading {
    fn of(title: &str, artist: &str) -> Self {
        Self {
            title: enrich::without_brackets_that(title, a_video_qualifier).to_owned(),
            artist: artist.to_owned(),
        }
    }
}

fn a_video_qualifier(inside: &str) -> bool {
    VIDEO_QUALIFIERS.contains(&folded_title(inside).as_str())
}

fn channel_named(artist: &str) -> Option<&str> {
    let artist = artist.trim();
    let artist = artist
        .strip_suffix(AN_AUTOGENERATED_CHANNEL)
        .unwrap_or(artist)
        .trim();
    (!artist.is_empty()).then_some(artist)
}

fn as_billed(title: &str) -> Option<(&str, &str)> {
    let (before, after) = title.split_once(BETWEEN_ARTIST_AND_TITLE)?;
    let (before, after) = (before.trim(), after.trim());
    (!before.is_empty() && !after.is_empty()).then_some((before, after))
}

fn readings_of(title: &str, artist: Option<&str>) -> Vec<Reading> {
    let artist = artist.and_then(channel_named);
    let mut readings = Vec::new();
    match (as_billed(title), artist) {
        (Some((before, after)), Some(artist)) if enrich::names_agree(before, artist) => {
            readings.push(Reading::of(after, artist));
        }
        (billed, artist) => {
            if let Some((before, after)) = billed {
                readings.push(Reading::of(after, before));
            }
            if let Some(artist) = artist {
                readings.push(Reading::of(title, artist));
            }
        }
    }
    readings.dedup();
    readings
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Footage {
    Heard,
    Filmed,
}

impl Footage {
    pub(crate) fn of(link: &SongLink) -> Self {
        match link {
            SongLink::Elsewhere(page) if Service::of_url(page) == Service::Youtube => Self::Filmed,
            SongLink::MusicBrainz(_) | SongLink::Deezer(_) | SongLink::Elsewhere(_) => Self::Heard,
        }
    }
}

pub(crate) fn the_song_searched_for(
    reference: &dyn Reference,
    song: &LinkNames,
    footage: Footage,
) -> Result<Option<Recording>> {
    let Some(title) = song.title.as_deref() else {
        return Ok(None);
    };
    let readings = readings_of(title, song.artist.as_deref());

    if let Some(heard) = the_first_named(reference, &readings, song.length, |found, named| {
        enrich::the_recording_named(found, named)
    })? {
        return Ok(Some(heard));
    }
    let Some(ran) = song.length.filter(|_| footage == Footage::Filmed) else {
        return Ok(None);
    };

    the_first_named(reference, &readings, None, |found, named| {
        enrich::the_recording_a_video_names(found, named, ran)
    })
}

fn the_first_named(
    reference: &dyn Reference,
    readings: &[Reading],
    length: Option<Duration>,
    taken: impl Fn(Vec<RecordingMatch>, &NamedAs<'_>) -> Option<RecordingMatch>,
) -> Result<Option<Recording>> {
    for reading in readings {
        let named = NamedAs {
            title: &reading.title,
            artist: Some((&reading.artist, None)),
            length,
        };
        for wording in [Wording::Phrase, Wording::Words] {
            let found = reference.find_recording(&RecordingAsked {
                title: reading.title.clone(),
                artist: Some(reading.artist.clone()),
                artist_mbid: None,
                release: None,
                length,
                wording,
            })?;
            if let Some(top) = taken(found, &named) {
                return Ok(Some(
                    reference
                        .recording(&top.recording)?
                        .unwrap_or_else(|| top.into_recording()),
                ));
            }
        }
    }

    Ok(None)
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct NamedAlbum {
    group: Mbid,
    release: Option<Mbid>,
    title: String,
    credit: Vec<Credit>,
}

impl NamedAlbum {
    fn billed(credit: &[Credit]) -> Option<String> {
        let billed = credited_as(credit);
        (!billed.trim().is_empty()).then_some(billed)
    }

    pub(crate) fn linked(self) -> Linked {
        Linked::Album {
            artist: Self::billed(&self.credit),
            group: self.group,
            release: self.release,
            title: self.title,
        }
    }
}

pub(crate) fn album_named(
    reference: &dyn Reference,
    link: &AlbumLink,
) -> Result<Option<NamedAlbum>> {
    match link {
        AlbumLink::Group(group) => Ok(reference.release_group(group)?.map(|group| NamedAlbum {
            group: group.id,
            release: None,
            title: group.title,
            credit: group.credit,
        })),
        AlbumLink::Release(release) => Ok(reference.release(release)?.and_then(|release| {
            Some(NamedAlbum {
                group: release.group?,
                release: Some(release.id),
                title: release.title,
                credit: release.credit,
            })
        })),
        AlbumLink::Deezer(_) | AlbumLink::Elsewhere(_) => {
            let Some(names) = reference.album_linked(link)? else {
                return Ok(None);
            };
            for barcode in &names.barcodes {
                let found = reference.releases_by_barcode(barcode)?;
                if let Some(named) = the_release_barcoded(found, barcode) {
                    return Ok(Some(named));
                }
            }
            Ok(None)
        }
    }
}

pub(crate) fn the_release_barcoded(
    found: Vec<BarcodeMatch>,
    barcode: &Barcode,
) -> Option<NamedAlbum> {
    let barcoded: Vec<BarcodeMatch> = found
        .into_iter()
        .filter(|found| {
            found.group.is_some()
                && found
                    .barcode
                    .as_deref()
                    .is_some_and(|stated| barcode.names(stated))
        })
        .collect();
    let groups: AHashSet<&Mbid> = barcoded
        .iter()
        .filter_map(|found| found.group.as_ref())
        .collect();
    if groups.len() > 1 {
        tracing::debug!(%barcode, groups = groups.len(), "a barcode names releases in several groups, so it names none");
        return None;
    }

    let taken = barcoded.into_iter().next()?;
    Some(NamedAlbum {
        group: taken.group?,
        release: Some(taken.release),
        title: taken.title,
        credit: taken.credit,
    })
}

pub(crate) fn album_held(connection: &Connection, named: &NamedAlbum) -> Result<Option<Linked>> {
    let held = connection
        .query_row(
            HELD_ALBUM,
            params![
                named.group.as_str(),
                named.release.as_ref().map(Mbid::as_str)
            ],
            |row| {
                Ok((
                    row.get::<_, i64>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, Option<String>>(2)?,
                    row.get::<_, i64>(3)?,
                ))
            },
        )
        .optional()
        .map_err(|source| Error::store(StoreOp::Query, source))?;
    let Some((album, title, artist, missing)) = held else {
        return Ok(None);
    };

    Ok(Some(Linked::HeldAlbum {
        album: AlbumId::new(album as u64)?,
        title,
        artist,
        missing: u32::try_from(missing).unwrap_or(u32::MAX),
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    const RECORDING: &str = "a6ab8ab1-5d0a-4c3c-a1a7-d6e8e5ec33a0";
    const GROUP: &str = "082c6aff-a7cc-36e0-a960-35a578ecd937";
    const RELEASE: &str = "98c0cd5f-fa84-45d9-839f-cc5d276dd5be";
    const ANOTHER_GROUP: &str = "11111111-1111-4111-8111-111111111111";

    fn mbid(id: &str) -> Mbid {
        Mbid::new(id).expect("a well-formed mbid")
    }

    fn elsewhere(url: &str) -> Option<SongLink> {
        Some(SongLink::Elsewhere(url.to_owned()))
    }

    fn an_album_elsewhere(url: &str) -> Option<AlbumLink> {
        Some(AlbumLink::Elsewhere(url.to_owned()))
    }

    #[test]
    fn a_link_to_a_song_on_a_service_is_read_as_one() {
        assert_eq!(
            SongLink::read("https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT?si=0a1b2c"),
            elsewhere("https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT?si=0a1b2c")
        );
        assert_eq!(
            SongLink::read("spotify:track:4cOdK2wGLETKBW3PvgPWqT"),
            elsewhere("https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT")
        );
        assert_eq!(
            SongLink::read("  https://tidal.com/browse/track/491206012  "),
            elsewhere("https://tidal.com/browse/track/491206012")
        );
        assert_eq!(
            SongLink::read("https://song.link/s/4cOdK2wGLETKBW3PvgPWqT"),
            elsewhere("https://song.link/s/4cOdK2wGLETKBW3PvgPWqT")
        );
        assert!(
            SongLink::read("https://music.apple.com/us/album/x/1559523357?i=1559523359").is_some()
        );
        assert!(SongLink::read("https://music.youtube.com/watch?v=dQw4w9WgXcQ").is_some());
        assert!(SongLink::read("https://youtu.be/dQw4w9WgXcQ").is_some());
        assert!(
            SongLink::read("https://soundcloud.com/rick-astley-official/never-gonna-give-you-up-4")
                .is_some()
        );
    }

    #[test]
    fn a_deezer_track_and_a_musicbrainz_recording_are_read_by_their_ids() {
        assert_eq!(
            SongLink::read("https://www.deezer.com/en/track/781592622"),
            Some(SongLink::Deezer(781_592_622))
        );
        assert_eq!(
            SongLink::read(&format!("https://musicbrainz.org/recording/{RECORDING}")),
            Some(SongLink::MusicBrainz(mbid(RECORDING)))
        );
    }

    #[test]
    fn words_albums_artists_and_other_pages_are_not_song_links() {
        for text in [
            "never gonna give you up",
            "https://open.spotify.com/album/6eUW0wxWtzkFdaEFsTJto6",
            "https://open.spotify.com/artist/0gxyHStUsqpMadRV0Di1Qt",
            "https://www.deezer.com/album/12345",
            "https://soundcloud.com/rick-astley-official/sets/whenever",
            "https://soundcloud.com/rick-astley-official",
            "https://www.youtube.com/@RickAstleyYT",
            "https://example.com/track/1",
            "https://musicbrainz.org/release/a6ab8ab1-5d0a-4c3c-a1a7-d6e8e5ec33a0",
            "https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT and more",
        ] {
            assert_eq!(SongLink::read(text), None, "{text}");
        }
    }

    #[test]
    fn a_link_to_an_album_on_a_service_is_read_as_one() {
        assert_eq!(
            AlbumLink::read("https://open.spotify.com/album/6N9PS4QXF1D0OWPk0Sxtb4?si=x"),
            an_album_elsewhere("https://open.spotify.com/album/6N9PS4QXF1D0OWPk0Sxtb4?si=x")
        );
        assert_eq!(
            AlbumLink::read("spotify:album:6N9PS4QXF1D0OWPk0Sxtb4"),
            an_album_elsewhere("https://open.spotify.com/album/6N9PS4QXF1D0OWPk0Sxtb4")
        );
        assert_eq!(
            AlbumLink::read("https://tidal.com/browse/album/492950065"),
            an_album_elsewhere("https://tidal.com/browse/album/492950065")
        );
        assert_eq!(
            AlbumLink::read("https://album.link/s/6N9PS4QXF1D0OWPk0Sxtb4"),
            an_album_elsewhere("https://album.link/s/6N9PS4QXF1D0OWPk0Sxtb4")
        );
        assert!(
            AlbumLink::read(
                "https://music.apple.com/gb/album/whenever-you-need-somebody/1559523357"
            )
            .is_some()
        );
        assert!(AlbumLink::read("https://music.amazon.com/albums/B0DZTQLXGX").is_some());
        assert!(
            AlbumLink::read(
                "https://music.youtube.com/playlist?list=OLAK5uy_kq2V0jSBZ1sgV9BFMyZZgdJvfNTI8sV9o"
            )
            .is_some()
        );
        assert_eq!(
            AlbumLink::read("https://www.deezer.com/fr/album/214959662"),
            Some(AlbumLink::Deezer(214_959_662))
        );
        assert_eq!(
            AlbumLink::read(&format!("https://musicbrainz.org/release/{RELEASE}")),
            Some(AlbumLink::Release(mbid(RELEASE)))
        );
        assert_eq!(
            AlbumLink::read(&format!("https://musicbrainz.org/release-group/{GROUP}/")),
            Some(AlbumLink::Group(mbid(GROUP)))
        );
    }

    #[test]
    fn a_song_an_artist_a_playlist_and_words_are_not_album_links() {
        for text in [
            "whenever you need somebody",
            "https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT",
            "https://open.spotify.com/artist/0gxyHStUsqpMadRV0Di1Qt",
            "https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M",
            "https://music.apple.com/us/album/x/1559523357?i=1559523359",
            "https://music.amazon.com/albums/B0DZTQLXGX?trackAsin=B0DZTSF3YS",
            "https://music.youtube.com/playlist?list=PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i",
            "https://www.deezer.com/track/781592622",
            "https://musicbrainz.org/artist/0383dadf-2a4e-4d10-a46a-e9e041da8eb3",
            "https://example.com/album/1",
            "https://open.spotify.com/album/6N9PS4QXF1D0OWPk0Sxtb4 too",
        ] {
            assert_eq!(AlbumLink::read(text), None, "{text}");
        }
    }

    #[test]
    fn a_link_to_a_playlist_on_a_service_that_shows_one_is_read_as_one_and_nothing_else_is() {
        const PLAYLIST: &str = "d20c6058-b625-49ec-ab78-99cf15584b3d";

        assert_eq!(
            FollowedLink::read("https://www.deezer.com/fr/playlist/3155776842?utm_source=deezer"),
            Some(FollowedLink::Playlist(PlaylistLink::Deezer(3_155_776_842)))
        );
        assert_eq!(
            FollowedLink::read(&format!("https://listenbrainz.org/playlist/{PLAYLIST}/")),
            Some(FollowedLink::Playlist(PlaylistLink::ListenBrainz(mbid(
                PLAYLIST
            ))))
        );
        assert_eq!(
            FollowedLink::read(
                "https://open.spotify.com/intl-de/playlist/37i9dQZF1DXcBWIGoYBM5M?si=x"
            ),
            Some(FollowedLink::Playlist(PlaylistLink::Spotify(
                "37i9dQZF1DXcBWIGoYBM5M".to_owned()
            )))
        );
        assert_eq!(
            FollowedLink::read("spotify:playlist:37i9dQZF1DXcBWIGoYBM5M"),
            Some(FollowedLink::Playlist(PlaylistLink::Spotify(
                "37i9dQZF1DXcBWIGoYBM5M".to_owned()
            )))
        );
        assert_eq!(
            FollowedLink::read(
                "https://music.apple.com/us/playlist/todays-hits/pl.f4d106fed2bd41149aaacabb233eb5eb"
            ),
            Some(FollowedLink::Playlist(PlaylistLink::AppleMusic {
                storefront: "us".to_owned(),
                id: "pl.f4d106fed2bd41149aaacabb233eb5eb".to_owned(),
            }))
        );
        assert_eq!(
            FollowedLink::read(
                "https://www.youtube.com/playlist?list=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI&si=x"
            ),
            Some(FollowedLink::Playlist(PlaylistLink::Youtube(
                "PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI".to_owned()
            )))
        );
        assert_eq!(
            PlaylistLink::read(
                "https://music.youtube.com/playlist?list=PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i"
            ),
            Some(PlaylistLink::Youtube(
                "PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i".to_owned()
            ))
        );
        assert!(matches!(
            FollowedLink::read("https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=PL4fGSI1pDJn6p"),
            Some(FollowedLink::Song(_))
        ));
        assert_eq!(
            PlaylistLink::read("https://music.apple.com/gb/playlist/pl.u-AkAmPlyUxEAm9V?l=en"),
            Some(PlaylistLink::AppleMusic {
                storefront: "gb".to_owned(),
                id: "pl.u-AkAmPlyUxEAm9V".to_owned(),
            })
        );
        for text in [
            "https://www.deezer.com/playlist/a-name",
            "https://listenbrainz.org/playlist/not-an-id",
            "https://music.apple.com/us/playlist/todays-hits",
            "https://music.youtube.com/playlist?list=OLAK5uy_kq2V0jSBZ1sgV9BFMyZZgdJvfNTI8sV9o",
            "https://www.youtube.com/playlist",
            "https://www.youtube.com/playlist?list=not%20an%20id",
            "https://music.apple.com/usa/playlist/x/pl.f4d106fed2bd41149aaacabb233eb5eb",
            "https://music.apple.com/us/album/x/pl.f4d106fed2bd41149aaacabb233eb5eb",
            "https://listenbrainz.org/user/rob/playlists",
            "https://open.spotify.com/playlist/not-an-id",
            "https://www.deezer.com/playlist/3155776842 too",
        ] {
            assert_eq!(PlaylistLink::read(text), None, "{text}");
        }
    }

    #[test]
    fn a_link_to_an_artist_on_any_service_is_read_as_one_and_nothing_else_is() {
        const ARTIST: &str = "0383dadf-2a4e-4d10-a46a-e9e041da8eb3";

        assert_eq!(
            ArtistLink::read(&format!("https://musicbrainz.org/artist/{ARTIST}/releases")),
            Some(ArtistLink::MusicBrainz(mbid(ARTIST)))
        );
        assert_eq!(
            ArtistLink::read("https://www.deezer.com/fr/artist/7307038?utm_source=x"),
            Some(ArtistLink::Deezer(7_307_038))
        );
        assert_eq!(
            FollowedLink::read(&format!("https://musicbrainz.org/artist/{ARTIST}")),
            Some(FollowedLink::Artist(ArtistLink::MusicBrainz(mbid(ARTIST))))
        );
        assert_eq!(
            FollowedLink::read("https://open.spotify.com/artist/0gxyHStUsqpMadRV0Di1Qt"),
            Some(FollowedLink::Artist(ArtistLink::Elsewhere(
                "https://open.spotify.com/artist/0gxyHStUsqpMadRV0Di1Qt".to_owned()
            )))
        );
        for text in [
            "https://open.spotify.com/artist/",
            "https://soundcloud.com/discover",
            "https://music.apple.com/us/artist/a-name",
            "https://musicbrainz.org/artist/not-an-id",
            "https://www.deezer.com/artist/a-name",
            "https://www.deezer.com/track/781592622",
            "https://musicbrainz.org/artist/0383dadf-2a4e-4d10-a46a-e9e041da8eb3 too",
        ] {
            assert_eq!(ArtistLink::read(text), None, "{text}");
        }
    }

    #[test]
    fn an_artist_page_is_written_as_musicbrainz_stores_it() {
        let page = |text: &str| match ArtistLink::read(text) {
            Some(ArtistLink::Elsewhere(page)) => page,
            other => panic!("{text} read as {other:?}"),
        };

        for (text, stored) in [
            (
                "https://open.spotify.com/intl-de/artist/3YQKmKGau1PzlVlkL1iodx?si=x1",
                "https://open.spotify.com/artist/3YQKmKGau1PzlVlkL1iodx",
            ),
            (
                "spotify:artist:3YQKmKGau1PzlVlkL1iodx",
                "https://open.spotify.com/artist/3YQKmKGau1PzlVlkL1iodx",
            ),
            (
                "https://music.apple.com/gb/artist/twenty-one-pilots/349736311",
                "https://music.apple.com/gb/artist/349736311",
            ),
            (
                "https://listen.tidal.com/artist/4664877",
                "https://tidal.com/artist/4664877",
            ),
            (
                "https://tidal.com/browse/artist/4664877?u",
                "https://tidal.com/artist/4664877",
            ),
            (
                "https://music.youtube.com/channel/UCBnZ16ahKA2DZ_T5W0FPUXg",
                "https://music.youtube.com/channel/UCBnZ16ahKA2DZ_T5W0FPUXg",
            ),
            (
                "https://m.youtube.com/channel/UCBnZ16ahKA2DZ_T5W0FPUXg",
                "https://www.youtube.com/channel/UCBnZ16ahKA2DZ_T5W0FPUXg",
            ),
            (
                "https://soundcloud.com/TwentyOnePilots",
                "https://soundcloud.com/twentyonepilots",
            ),
            (
                "https://twentyonepilots.bandcamp.com/",
                "https://twentyonepilots.bandcamp.com/",
            ),
        ] {
            assert_eq!(page(text), stored, "{text}");
        }
        assert_eq!(
            ArtistLink::read("https://music.apple.com/gb/artist/x/349736311")
                .map(|link| link.pages()),
            Some(vec![
                "https://music.apple.com/gb/artist/349736311".to_owned(),
                "https://music.apple.com/us/artist/349736311".to_owned(),
            ])
        );
        assert_eq!(
            ArtistLink::Deezer(7_307_038).pages(),
            ["https://www.deezer.com/artist/7307038"]
        );
    }

    #[test]
    fn a_followed_link_is_a_song_where_it_names_one_and_an_album_where_it_names_that() {
        assert_eq!(
            FollowedLink::read("https://music.apple.com/us/album/x/1559523357?i=1559523359")
                .map(|link| matches!(link, FollowedLink::Song(_))),
            Some(true)
        );
        assert_eq!(
            FollowedLink::read("https://music.apple.com/us/album/x/1559523357")
                .map(|link| matches!(link, FollowedLink::Album(_))),
            Some(true)
        );
        assert!(is_a_followed_link("https://www.deezer.com/album/12345"));
        assert!(is_a_followed_link(
            "https://open.spotify.com/artist/0gxyHStUsqpMadRV0Di1Qt"
        ));
        assert!(is_a_followed_link(
            "https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M"
        ));
        assert!(!is_a_followed_link("deezer album"));
    }

    #[test]
    fn an_album_page_is_asked_of_album_link_and_one_of_its_own_pages_as_it_stands() {
        assert_eq!(
            AlbumLink::read("https://open.spotify.com/album/6N9PS4QXF1D0OWPk0Sxtb4")
                .and_then(|link| link.page()),
            Some(
                "https://album.link/https%3A%2F%2Fopen.spotify.com%2Falbum%2F6N9PS4QXF1D0OWPk0Sxtb4"
                    .to_owned()
            )
        );
        assert_eq!(
            AlbumLink::read("https://album.link/s/6N9PS4QXF1D0OWPk0Sxtb4")
                .and_then(|link| link.page()),
            Some("https://album.link/s/6N9PS4QXF1D0OWPk0Sxtb4".to_owned())
        );
        assert_eq!(AlbumLink::Deezer(1).page(), None);
    }

    #[test]
    fn a_barcode_names_the_same_code_however_many_zeros_lead_it() {
        let upc = Barcode::new("035627515026").expect("a twelve-digit barcode");

        assert!(upc.names("035627515026"));
        assert!(upc.names("0035627515026"));
        assert!(upc.names("35627515026"));
        assert!(!upc.names("035627515027"));
        assert!(!upc.names("0356275150260"));
        assert!(!upc.names("03562751502X"));
        assert_eq!(upc.spellings(), ["035627515026", "0035627515026"]);
        assert_eq!(
            Barcode::new("5099902894225")
                .expect("a thirteen-digit barcode")
                .spellings(),
            ["5099902894225"]
        );
        assert_eq!(Barcode::new("12345"), None);
        assert_eq!(Barcode::new("12345678901234567"), None);
        assert_eq!(Barcode::new("0356-2751-5026"), None);
    }

    fn barcoded(release: &str, group: Option<&str>, barcode: &str) -> BarcodeMatch {
        BarcodeMatch {
            release: mbid(release),
            group: group.map(mbid),
            barcode: Some(barcode.to_owned()),
            title: "Whenever You Need Somebody".to_owned(),
            credit: vec![Credit {
                name: "Rick Astley".to_owned(),
                joined_by: String::new(),
                mbid: None,
            }],
        }
    }

    #[test]
    fn a_release_is_taken_by_its_barcode_only_where_the_code_agrees_and_names_one_group() {
        let upc = Barcode::new("035627515026").expect("a barcode");
        let taken = the_release_barcoded(
            vec![
                barcoded(RECORDING, Some(ANOTHER_GROUP), "5099902894225"),
                barcoded(RELEASE, Some(GROUP), "0035627515026"),
            ],
            &upc,
        )
        .map(NamedAlbum::linked);

        assert_eq!(
            taken,
            Some(Linked::Album {
                group: mbid(GROUP),
                release: Some(mbid(RELEASE)),
                title: "Whenever You Need Somebody".to_owned(),
                artist: Some("Rick Astley".to_owned()),
            })
        );
        assert_eq!(
            the_release_barcoded(
                vec![
                    barcoded(RELEASE, Some(GROUP), "035627515026"),
                    barcoded(RECORDING, Some(ANOTHER_GROUP), "035627515026"),
                ],
                &upc
            ),
            None,
            "a code two groups share names neither"
        );
        assert_eq!(
            the_release_barcoded(vec![barcoded(RELEASE, None, "035627515026")], &upc),
            None
        );
        assert_eq!(
            the_release_barcoded(vec![barcoded(RELEASE, Some(GROUP), "5099902894225")], &upc),
            None,
            "a release found under another code is no match"
        );
    }

    fn reading(title: &str, artist: &str) -> Reading {
        Reading {
            title: title.to_owned(),
            artist: artist.to_owned(),
        }
    }

    #[test]
    fn an_upload_titled_artist_dash_song_is_read_as_that_song_by_that_artist() {
        assert_eq!(
            readings_of(
                "Rick Astley - Never Gonna Give You Up (Official Music Video)",
                Some("Rick Astley")
            ),
            [reading("Never Gonna Give You Up", "Rick Astley")]
        );
        assert_eq!(
            readings_of(
                "Rick Astley - Never Gonna Give You Up [Official Video] (4K Remaster)",
                Some("RickAstleyVEVO")
            ),
            [
                reading(
                    "Never Gonna Give You Up [Official Video] (4K Remaster)",
                    "Rick Astley"
                ),
                reading(
                    "Rick Astley - Never Gonna Give You Up [Official Video] (4K Remaster)",
                    "RickAstleyVEVO"
                ),
            ],
            "a bracket outside the closed list stays, and so does whatever stands before it"
        );
        assert_eq!(
            readings_of(
                "Never Gonna Give You Up (Audio)",
                Some("Rick Astley - Topic")
            ),
            [reading("Never Gonna Give You Up", "Rick Astley")]
        );
        assert_eq!(
            readings_of("Never Gonna Give You Up (Live)", Some("Rick Astley")),
            [reading("Never Gonna Give You Up (Live)", "Rick Astley")],
            "a take that is another recording keeps what says so"
        );
        assert!(readings_of("Never Gonna Give You Up", None).is_empty());
        assert_eq!(readings_of("Official Video", Some("Rick Astley")).len(), 1);
    }

    fn take(id: &str, seconds: Option<u64>) -> Recording {
        Recording {
            id: mbid(id),
            title: "Never Gonna Give You Up".to_owned(),
            credit: Vec::new(),
            length: seconds.map(Duration::from_secs),
            isrcs: Vec::new(),
            releases: Vec::new(),
        }
    }

    #[test]
    fn of_the_takes_an_isrc_names_the_one_whose_length_agrees_is_taken() {
        let video = take("11111111-1111-4111-8111-111111111111", Some(232));
        let single = take("22222222-2222-4222-8222-222222222222", Some(213));
        let untimed = take("33333333-3333-4333-8333-333333333333", None);

        assert_eq!(
            the_take_linked(
                vec![video.clone(), untimed.clone(), single.clone()],
                Some(Duration::from_secs(214))
            ),
            Some(single)
        );
        assert_eq!(
            the_take_linked(vec![video.clone()], Some(Duration::from_secs(214))),
            None
        );
        assert_eq!(
            the_take_linked(vec![video.clone(), untimed], None),
            Some(video)
        );
    }
}
